export enum EstadoExpediente {
    EN_REVISION = 'EN_REVISION',
    PENDIENTE_RESUBIDA = 'PENDIENTE_RESUBIDA',
    APROBADO = 'APROBADO',
    FINALIZADO = 'FINALIZADO',
    INICIADO = 'INICIADO',
    RECHAZADO = 'RECHAZADO'
}
