export enum EstadoDocumento {
    PENDIENTE_CARGA = 'PENDIENTE_CARGA',
    CARGADO = 'CARGADO',
    EN_REVISION = 'EN_REVISION',
    APROBADO = 'APROBADO',
    PENDIENTE_RESUBIDA = 'PENDIENTE_RESUBIDA',
    SUBIDO_A_GDE = 'SUBIDO_A_GDE'
}
